# Generated by Django 4.0.5 on 2022-08-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_page',
            field=models.URLField(default='/'),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/'),
        ),
    ]
