# Generated by Django 4.0.5 on 2022-08-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_items_item_page_alter_items_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_page',
            field=models.CharField(max_length=200),
        ),
    ]
