# Generated by Django 4.0.5 on 2022-08-15 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_items_item_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.RemoveField(
            model_name='items',
            name='item_id',
        ),
        migrations.AlterField(
            model_name='items',
            name='item_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
