# Generated by Django 4.0.5 on 2022-08-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_cart_remove_items_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_price',
            field=models.CharField(max_length=20),
        ),
    ]
